// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5f4tos_tVCnQSDnUaoU_qU_tlLm7fJ0',
    appId: '1:394017485973:ios:102733a3b2ed5fad56979c',
    messagingSenderId: '394017485973',
    projectId: 'gocery-ae5d1',
    storageBucket: 'gocery-ae5d1.firebasestorage.app',
    iosClientId: '394017485973-brtjhvp99avjvro5mgtv5i8gqjdk7qg9.apps.googleusercontent.com',
    iosBundleId: 'com.ios.gocery',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzE-XKCPincPZQPKXUr5vR4KlZafk7Bv0',
    appId: '1:394017485973:web:695ffcb383933d8f56979c',
    messagingSenderId: '394017485973',
    projectId: 'gocery-ae5d1',
    authDomain: 'gocery-ae5d1.firebaseapp.com',
    storageBucket: 'gocery-ae5d1.firebasestorage.app',
    measurementId: 'G-KCP9C03LE8',
  );

}